---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  template:
    spec:
      containers:
        - name: mysql
          volumeMounts:
            - name: database-data
              mountPath: "/var/lib/mysql"
          env:
            - name: MYSQL_DATABASE
              value: admin
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: database