---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app.kubernetes.io/name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: database
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: skyway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database
    spec:
      containers:
        - name: mysql
          image: mysql:5.7.22
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
              name: mysql
