---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: database
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: skyway
  ports:
    - name: mysql
      port: 3306
  clusterIP: None